### ISSUE TITLE
cannot upload any parameter file for public submission

### ISSUE THREAD

**Issue by mlocardpaulet** [Proteobench/ProteoBench#191] opened 2024-01-05 12:37 UTC
I tried uploading Proline outputs with the xlsx file that contains the tab for the plot data as well as the tabs with the parameter information, but when I upload it in the field `Meta data for searches`, the file name appears under the upload box but disappears after a few seconds. And then I cannot do anything more. 
Did I understand well? For Proline the idea is to submit the same xlsx table for figure generation and public submission, right?

**Comment by enryH** [comment] 2024-01-05 15:35
I have not worked on the front end for now. I say that for Proline, the parameter upload should be deactivated as the outputs and parameters are as you said in one xlsx excel file with many sheets. I will try to reproduce the bug and see if I can find something in the logs...

**Comment by scaramonche** [comment] 2024-01-05 17:59
I checked and as far as I can find out, the issue is not related to the parsing of parameters, but with the file upload button, which doesn't work. So, right now it is broken also for the params files of any software. I think it might be related to the unique identifier of the element since I get a functioning button once I remove that. Not sure why though. Also this is not a permanent solution, because without the unique id, I get the error of non-unique streamlit element. 
@RobbinBouwmeester any idea?

**Comment by RobbinBouwmeester** [comment] 2024-01-06 09:59
Looking into this right now... It is strange, it should not reload the elements, but somehow it does.

**Comment by RobbinBouwmeester** [comment] 2024-01-06 12:18
Fixed in #192

**Comment by RobbinBouwmeester** [comment] 2024-01-06 12:19
Very important though is that you use the new secrets.toml! Otherwise you will not be able to open a PR.

Previous token had an expiration of a year, so it had to be renewed.

**Comment by scaramonche** [comment] 2024-01-07 12:36
Where do we get the new secrets.toml from?

**Closed** 2024-01-07 15:30 UTC
Labels: bug
